spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo
    username: root
    password: 31234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update